### ISSUE TITLE
No longer works with tree-sitter-php versions 0.23.0 or later

### ISSUE THREAD

**Issue by solstag** [claytonrcarter/tree-sitter-phpdoc#43]
Ni! From version 0.23.0 [tree-sitter-php](https://github.com/tree-sitter/tree-sitter-php) no longer provides rule `namespace_aliasing_clause` used in current version (0.1.6) `grammar.js` line 514: https://github.com/claytonrcarter/tree-sitter-phpdoc/blob/v0.1.6/grammar.js#L514

In case it may be useful, I found the issue [here](https://codeberg.org/guix/guix/issues/2730) while preparing a Guix package definition.

Cheers

**Comment by Roardom** [comment]
Hi @calebdw,

I see you removed the `namespace_aliasing_clause` rule here: https://github.com/tree-sitter/tree-sitter-php/pull/247/commits/5b47c5a76336e26440f3b0c67666010e3d2afc11

I'm not too familiar with tree-sitter grammars, but is there a replacement for this rule?

**Comment by calebdw** [comment]
@Roardom, I've fixed in #44

**Comment by claytonrcarter** [comment]
Thank you for reporting and thank you @calebdw for the fix. This is now fixed on master and tagged in `v0.1.7`.

**Comment by solstag** [comment]
Hi, and thank you @claytonrcarter and @calebdw. However I'm still facing an issue when building.

I've tried building with `tree-sitter-php` versions `0.23.0`, `0.23.2` and `0.24.2`.

```
file:///tmp/guix-build-tree-sitter-phpdoc-0.1.7.drv-0/source/[eval1]:330
        throw new Error(`Rule '${ruleName}' returned undefined.`);
              ^

Error: Rule '_type' returned undefined.
    at grammar (file:///tmp/guix-build-tree-sitter-phpdoc-0.1.7.drv-0/source/[eval1]:330:15)
    at Object.<anonymous> (/tmp/guix-build-tree-sitter-phpdoc-0.1.7.drv-0/source/grammar.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at cjsLoader (node:internal/modules/esm/translators:262:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:196:7)

Node.js v22.14.0
Error when generating parser

Caused by:
    Failed to load grammar.js -- `node` process exited with status 1
```

The rule involved and the error message are a bit different from the other case: `Error: Rule '_type' returned undefined.` and does not point to a specific line in phpdoc. You can see the previous error message [here](https://codeberg.org/guix/guix/issues/2730#issuecomment-8847441).

Any ideas? Should I open a different issue?

**Comment by claytonrcarter** [comment]
@solstag you're right, this was closed prematurely. This tree-sitter grammar reuses many of the grammar rules from the PHP grammar because so much of syntax of PHPDoc types are shared from PHP. This avoids us needing to redefine basic syntax here and, it was my hope, would make this grammar always align w/ the core PHP syntax.

However, my recollection is that reusing grammars like this is "off label", and it has been sort of hard to debug, such as here.

Anyway, it looks like the `_type` rule that we're reusing was [renamed to just `type` in v0.22.3](https://github.com/tree-sitter/tree-sitter-php/compare/v0.22.2...v0.22.3#diff-d7f2790ddd722aa06dcaa2e952f6634e64a9704c10d0b02866b8f014ef21601dL522)[^1] (we currently use v0.22.2) so this should be an easy fix.

[^1]: You have to view the "Files Changed" tab, and then expand the diff for `common/define-grammar.js` for that link to work.

**Comment by claytonrcarter** [comment]
`master` is now updated to use v0.23 of the PHP grammar (via #45) but I'm running into problems moving to v0.24, in #46. Suggestions and help are encouraged and appreciated!

**Comment by solstag** [comment]
Great, thank you. I can confirm that with ts-php-0.23 it works for me as well. Would you mind creating a new version tag from master so I can publish a more proper package recipe? I have it working on a local channel with a commit based recipe, but a version based recipe would be preferred for inclusion in Guix.

**Comment by claytonrcarter** [comment]
@solstag I think [v0.1.7](https://github.com/claytonrcarter/tree-sitter-phpdoc/releases/tag/v0.1.7) has this in it. Please confirm though

**Comment by solstag** [comment]
Thanks. I had tried v0.1.7, but it doesn't build, master does.

**Comment by claytonrcarter** [comment]
🤦 Sorry, you're right. You can try v0.1.8 now.

**Comment by solstag** [comment]
Yes, v0.1.8 builds just fine. Thank you!

**Comment by solstag** [comment]
Since there is #46 for 0.24 and this issue is about 0.23, and tree-sitter-phpdoc [has been merged in Guix](https://codeberg.org/guix/guix/pulls/5832), I'm closing. Cheers and thanks again!
